package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : import.h:56</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class _frozen extends StructObject {
	public _frozen() {
		super();
	}
	/// C type : char*
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char*
	@Field(0) 
	public _frozen name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/// C type : unsigned char*
	@Field(1) 
	public Pointer<Byte > code() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : unsigned char*
	@Field(1) 
	public _frozen code(Pointer<Byte > code) {
		this.io.setPointerField(this, 1, code);
		return this;
	}
	@Field(2) 
	public int size() {
		return this.io.getIntField(this, 2);
	}
	@Field(2) 
	public _frozen size(int size) {
		this.io.setIntField(this, 2, size);
		return this;
	}
	public _frozen(Pointer pointer) {
		super(pointer);
	}
}
