package com.heeere.python27;
import org.bridj.Callback;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : import.h:45</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class _inittab extends StructObject {
	public _inittab() {
		super();
	}
	/// C type : char*
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char*
	@Field(0) 
	public _inittab name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/// C type : initfunc_callback
	@Field(1) 
	public Pointer<_inittab.initfunc_callback > initfunc() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : initfunc_callback
	@Field(1) 
	public _inittab initfunc(Pointer<_inittab.initfunc_callback > initfunc) {
		this.io.setPointerField(this, 1, initfunc);
		return this;
	}
	/// <i>native declaration : import.h:44</i>
	/// <i>native declaration : import.h:44</i>
	public static abstract class initfunc_callback extends Callback<initfunc_callback > {
		abstract public void apply();
	};
	public _inittab(Pointer pointer) {
		super(pointer);
	}
}
