package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : complexobject.h:4</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class Py_complex extends StructObject {
	public Py_complex() {
		super();
	}
	@Field(0) 
	public double real() {
		return this.io.getDoubleField(this, 0);
	}
	@Field(0) 
	public Py_complex real(double real) {
		this.io.setDoubleField(this, 0, real);
		return this;
	}
	@Field(1) 
	public double imag() {
		return this.io.getDoubleField(this, 1);
	}
	@Field(1) 
	public Py_complex imag(double imag) {
		this.io.setDoubleField(this, 1, imag);
		return this;
	}
	public Py_complex(Pointer pointer) {
		super(pointer);
	}
}
