package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : code.h:45</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyAddrPair extends StructObject {
	public PyAddrPair() {
		super();
	}
	@Field(0) 
	public int ap_lower() {
		return this.io.getIntField(this, 0);
	}
	@Field(0) 
	public PyAddrPair ap_lower(int ap_lower) {
		this.io.setIntField(this, 0, ap_lower);
		return this;
	}
	@Field(1) 
	public int ap_upper() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public PyAddrPair ap_upper(int ap_upper) {
		this.io.setIntField(this, 1, ap_upper);
		return this;
	}
	public PyAddrPair(Pointer pointer) {
		super(pointer);
	}
}
