package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : pyerrors.h:6</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyBaseExceptionObject extends StructObject {
	public PyBaseExceptionObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PyBaseExceptionObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyBaseExceptionObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > dict() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PyBaseExceptionObject dict(Pointer<PyObject > dict) {
		this.io.setPointerField(this, 2, dict);
		return this;
	}
	/// C type : PyObject*
	@Field(3) 
	public Pointer<PyObject > args() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : PyObject*
	@Field(3) 
	public PyBaseExceptionObject args(Pointer<PyObject > args) {
		this.io.setPointerField(this, 3, args);
		return this;
	}
	/// C type : PyObject*
	@Field(4) 
	public Pointer<PyObject > message() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : PyObject*
	@Field(4) 
	public PyBaseExceptionObject message(Pointer<PyObject > message) {
		this.io.setPointerField(this, 4, message);
		return this;
	}
	public PyBaseExceptionObject(Pointer pointer) {
		super(pointer);
	}
}
