package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : bytearrayobject.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyByteArrayObject extends StructObject {
	public PyByteArrayObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PyByteArrayObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyByteArrayObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : Py_ssize_t
	@Field(2) 
	public Pointer<Py_ssize_t > ob_size() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : Py_ssize_t
	@Field(2) 
	public PyByteArrayObject ob_size(Pointer<Py_ssize_t > ob_size) {
		this.io.setPointerField(this, 2, ob_size);
		return this;
	}
	/**
	 * XXX(nnorwitz): should ob_exports be Py_ssize_t?<br>
	 * how many buffer exports
	 */
	@Field(3) 
	public int ob_exports() {
		return this.io.getIntField(this, 3);
	}
	/**
	 * XXX(nnorwitz): should ob_exports be Py_ssize_t?<br>
	 * how many buffer exports
	 */
	@Field(3) 
	public PyByteArrayObject ob_exports(int ob_exports) {
		this.io.setIntField(this, 3, ob_exports);
		return this;
	}
	/**
	 * How many bytes allocated<br>
	 * C type : Py_ssize_t
	 */
	@Field(4) 
	public Pointer<Py_ssize_t > ob_alloc() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * How many bytes allocated<br>
	 * C type : Py_ssize_t
	 */
	@Field(4) 
	public PyByteArrayObject ob_alloc(Pointer<Py_ssize_t > ob_alloc) {
		this.io.setPointerField(this, 4, ob_alloc);
		return this;
	}
	/// C type : char*
	@Field(5) 
	public Pointer<Byte > ob_bytes() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : char*
	@Field(5) 
	public PyByteArrayObject ob_bytes(Pointer<Byte > ob_bytes) {
		this.io.setPointerField(this, 5, ob_bytes);
		return this;
	}
	public PyByteArrayObject(Pointer pointer) {
		super(pointer);
	}
}
