package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : methodobject.h:37</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyCFunctionObject extends StructObject {
	public PyCFunctionObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PyCFunctionObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyCFunctionObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/**
	 * Description of the C function to call<br>
	 * C type : PyMethodDef*
	 */
	@Field(2) 
	public Pointer<PyMethodDef > m_ml() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * Description of the C function to call<br>
	 * C type : PyMethodDef*
	 */
	@Field(2) 
	public PyCFunctionObject m_ml(Pointer<PyMethodDef > m_ml) {
		this.io.setPointerField(this, 2, m_ml);
		return this;
	}
	/**
	 * Passed as 'self' arg to the C func, can be NULL<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public Pointer<PyObject > m_self() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * Passed as 'self' arg to the C func, can be NULL<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public PyCFunctionObject m_self(Pointer<PyObject > m_self) {
		this.io.setPointerField(this, 3, m_self);
		return this;
	}
	/**
	 * The __module__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public Pointer<PyObject > m_module() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * The __module__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public PyCFunctionObject m_module(Pointer<PyObject > m_module) {
		this.io.setPointerField(this, 4, m_module);
		return this;
	}
	public PyCFunctionObject(Pointer pointer) {
		super(pointer);
	}
}
