package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : classobject.h:12</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyClassObject extends StructObject {
	public PyClassObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PyClassObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyClassObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/**
	 * A tuple of class objects<br>
	 * C type : PyObject*
	 */
	@Field(2) 
	public Pointer<PyObject > cl_bases() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * A tuple of class objects<br>
	 * C type : PyObject*
	 */
	@Field(2) 
	public PyClassObject cl_bases(Pointer<PyObject > cl_bases) {
		this.io.setPointerField(this, 2, cl_bases);
		return this;
	}
	/**
	 * A dictionary<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public Pointer<PyObject > cl_dict() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * A dictionary<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public PyClassObject cl_dict(Pointer<PyObject > cl_dict) {
		this.io.setPointerField(this, 3, cl_dict);
		return this;
	}
	/**
	 * A string<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public Pointer<PyObject > cl_name() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * A string<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public PyClassObject cl_name(Pointer<PyObject > cl_name) {
		this.io.setPointerField(this, 4, cl_name);
		return this;
	}
	/**
	 * The following three are functions or NULL<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public Pointer<PyObject > cl_getattr() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * The following three are functions or NULL<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public PyClassObject cl_getattr(Pointer<PyObject > cl_getattr) {
		this.io.setPointerField(this, 5, cl_getattr);
		return this;
	}
	/// C type : PyObject*
	@Field(6) 
	public Pointer<PyObject > cl_setattr() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : PyObject*
	@Field(6) 
	public PyClassObject cl_setattr(Pointer<PyObject > cl_setattr) {
		this.io.setPointerField(this, 6, cl_setattr);
		return this;
	}
	/// C type : PyObject*
	@Field(7) 
	public Pointer<PyObject > cl_delattr() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : PyObject*
	@Field(7) 
	public PyClassObject cl_delattr(Pointer<PyObject > cl_delattr) {
		this.io.setPointerField(this, 7, cl_delattr);
		return this;
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(8) 
	public Pointer<PyObject > cl_weakreflist() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(8) 
	public PyClassObject cl_weakreflist(Pointer<PyObject > cl_weakreflist) {
		this.io.setPointerField(this, 8, cl_weakreflist);
		return this;
	}
	public PyClassObject(Pointer pointer) {
		super(pointer);
	}
}
