package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : funcobject.h:13</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyFunctionObject extends StructObject {
	public PyFunctionObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PyFunctionObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyFunctionObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/**
	 * A code object<br>
	 * C type : PyObject*
	 */
	@Field(2) 
	public Pointer<PyObject > func_code() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * A code object<br>
	 * C type : PyObject*
	 */
	@Field(2) 
	public PyFunctionObject func_code(Pointer<PyObject > func_code) {
		this.io.setPointerField(this, 2, func_code);
		return this;
	}
	/**
	 * A dictionary (other mappings won't do)<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public Pointer<PyObject > func_globals() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * A dictionary (other mappings won't do)<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public PyFunctionObject func_globals(Pointer<PyObject > func_globals) {
		this.io.setPointerField(this, 3, func_globals);
		return this;
	}
	/**
	 * NULL or a tuple<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public Pointer<PyObject > func_defaults() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * NULL or a tuple<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public PyFunctionObject func_defaults(Pointer<PyObject > func_defaults) {
		this.io.setPointerField(this, 4, func_defaults);
		return this;
	}
	/**
	 * NULL or a tuple of cell objects<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public Pointer<PyObject > func_closure() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * NULL or a tuple of cell objects<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public PyFunctionObject func_closure(Pointer<PyObject > func_closure) {
		this.io.setPointerField(this, 5, func_closure);
		return this;
	}
	/**
	 * The __doc__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(6) 
	public Pointer<PyObject > func_doc() {
		return this.io.getPointerField(this, 6);
	}
	/**
	 * The __doc__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(6) 
	public PyFunctionObject func_doc(Pointer<PyObject > func_doc) {
		this.io.setPointerField(this, 6, func_doc);
		return this;
	}
	/**
	 * The __name__ attribute, a string object<br>
	 * C type : PyObject*
	 */
	@Field(7) 
	public Pointer<PyObject > func_name() {
		return this.io.getPointerField(this, 7);
	}
	/**
	 * The __name__ attribute, a string object<br>
	 * C type : PyObject*
	 */
	@Field(7) 
	public PyFunctionObject func_name(Pointer<PyObject > func_name) {
		this.io.setPointerField(this, 7, func_name);
		return this;
	}
	/**
	 * The __dict__ attribute, a dict or NULL<br>
	 * C type : PyObject*
	 */
	@Field(8) 
	public Pointer<PyObject > func_dict() {
		return this.io.getPointerField(this, 8);
	}
	/**
	 * The __dict__ attribute, a dict or NULL<br>
	 * C type : PyObject*
	 */
	@Field(8) 
	public PyFunctionObject func_dict(Pointer<PyObject > func_dict) {
		this.io.setPointerField(this, 8, func_dict);
		return this;
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(9) 
	public Pointer<PyObject > func_weakreflist() {
		return this.io.getPointerField(this, 9);
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(9) 
	public PyFunctionObject func_weakreflist(Pointer<PyObject > func_weakreflist) {
		this.io.setPointerField(this, 9, func_weakreflist);
		return this;
	}
	/**
	 * The __module__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(10) 
	public Pointer<PyObject > func_module() {
		return this.io.getPointerField(this, 10);
	}
	/**
	 * The __module__ attribute, can be anything<br>
	 * C type : PyObject*
	 */
	@Field(10) 
	public PyFunctionObject func_module(Pointer<PyObject > func_module) {
		this.io.setPointerField(this, 10, func_module);
		return this;
	}
	public PyFunctionObject(Pointer pointer) {
		super(pointer);
	}
}
