package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : compile.h:15</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyFutureFeatures extends StructObject {
	public PyFutureFeatures() {
		super();
	}
	/// flags set by future statements
	@Field(0) 
	public int ff_features() {
		return this.io.getIntField(this, 0);
	}
	/// flags set by future statements
	@Field(0) 
	public PyFutureFeatures ff_features(int ff_features) {
		this.io.setIntField(this, 0, ff_features);
		return this;
	}
	/// line number of last future statement
	@Field(1) 
	public int ff_lineno() {
		return this.io.getIntField(this, 1);
	}
	/// line number of last future statement
	@Field(1) 
	public PyFutureFeatures ff_lineno(int ff_lineno) {
		this.io.setIntField(this, 1, ff_lineno);
		return this;
	}
	public PyFutureFeatures(Pointer pointer) {
		super(pointer);
	}
}
