package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : objimpl.h:54</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("python27") 
public class PyGC_Head extends StructObject {
	public PyGC_Head() {
		super();
	}
	/// C type : gc_struct
	@Field(0) 
	public PyGC_Head.gc_struct gc() {
		return this.io.getNativeObjectField(this, 0);
	}
	/// C type : gc_struct
	@Field(0) 
	public PyGC_Head gc(PyGC_Head.gc_struct gc) {
		this.io.setNativeObjectField(this, 0, gc);
		return this;
	}
	/// force worst-case alignment
	@Field(1) 
	public double dummy() {
		return this.io.getDoubleField(this, 1);
	}
	/// force worst-case alignment
	@Field(1) 
	public PyGC_Head dummy(double dummy) {
		this.io.setDoubleField(this, 1, dummy);
		return this;
	}
	/// <i>native declaration : objimpl.h:53</i>
	/// <i>native declaration : objimpl.h:53</i>
	public static class gc_struct extends StructObject {
		public gc_struct() {
			super();
		}
		/// C type : _gc_head*
		@Field(0) 
		public Pointer<PyGC_Head > gc_next() {
			return this.io.getPointerField(this, 0);
		}
		/// C type : _gc_head*
		@Field(0) 
		public gc_struct gc_next(Pointer<PyGC_Head > gc_next) {
			this.io.setPointerField(this, 0, gc_next);
			return this;
		}
		/// C type : _gc_head*
		@Field(1) 
		public Pointer<PyGC_Head > gc_prev() {
			return this.io.getPointerField(this, 1);
		}
		/// C type : _gc_head*
		@Field(1) 
		public gc_struct gc_prev(Pointer<PyGC_Head > gc_prev) {
			this.io.setPointerField(this, 1, gc_prev);
			return this;
		}
		/// C type : Py_ssize_t
		@Field(2) 
		public Pointer<Py_ssize_t > gc_refs() {
			return this.io.getPointerField(this, 2);
		}
		/// C type : Py_ssize_t
		@Field(2) 
		public gc_struct gc_refs(Pointer<Py_ssize_t > gc_refs) {
			this.io.setPointerField(this, 2, gc_refs);
			return this;
		}
		public gc_struct(Pointer pointer) {
			super(pointer);
		}
	};
	public PyGC_Head(Pointer pointer) {
		super(pointer);
	}
}
