package com.heeere.python27;
import com.heeere.python27.Python27Library.getter;
import com.heeere.python27.Python27Library.setter;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : descrobject.h:9</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyGetSetDef extends StructObject {
	public PyGetSetDef() {
		super();
	}
	/// C type : char*
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char*
	@Field(0) 
	public PyGetSetDef name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	/// C type : getter
	@Field(1) 
	public Pointer<getter > get() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : getter
	@Field(1) 
	public PyGetSetDef get(Pointer<getter > get) {
		this.io.setPointerField(this, 1, get);
		return this;
	}
	/// C type : setter
	@Field(2) 
	public Pointer<setter > set() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : setter
	@Field(2) 
	public PyGetSetDef set(Pointer<setter > set) {
		this.io.setPointerField(this, 2, set);
		return this;
	}
	/// C type : char*
	@Field(3) 
	public Pointer<Byte > doc() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : char*
	@Field(3) 
	public PyGetSetDef doc(Pointer<Byte > doc) {
		this.io.setPointerField(this, 3, doc);
		return this;
	}
	/// C type : void*
	@Field(4) 
	public Pointer<? > closure() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : void*
	@Field(4) 
	public PyGetSetDef closure(Pointer<? > closure) {
		this.io.setPointerField(this, 4, closure);
		return this;
	}
	public PyGetSetDef(Pointer pointer) {
		super(pointer);
	}
}
