package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : pystate.h:18</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyInterpreterState extends StructObject {
	public PyInterpreterState() {
		super();
	}
	/// C type : _is*
	@Field(0) 
	public Pointer<PyInterpreterState > next() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : _is*
	@Field(0) 
	public PyInterpreterState next(Pointer<PyInterpreterState > next) {
		this.io.setPointerField(this, 0, next);
		return this;
	}
	/// C type : _ts*
	@Field(1) 
	public Pointer<PyThreadState > tstate_head() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _ts*
	@Field(1) 
	public PyInterpreterState tstate_head(Pointer<PyThreadState > tstate_head) {
		this.io.setPointerField(this, 1, tstate_head);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > modules() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PyInterpreterState modules(Pointer<PyObject > modules) {
		this.io.setPointerField(this, 2, modules);
		return this;
	}
	/// C type : PyObject*
	@Field(3) 
	public Pointer<PyObject > sysdict() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : PyObject*
	@Field(3) 
	public PyInterpreterState sysdict(Pointer<PyObject > sysdict) {
		this.io.setPointerField(this, 3, sysdict);
		return this;
	}
	/// C type : PyObject*
	@Field(4) 
	public Pointer<PyObject > builtins() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : PyObject*
	@Field(4) 
	public PyInterpreterState builtins(Pointer<PyObject > builtins) {
		this.io.setPointerField(this, 4, builtins);
		return this;
	}
	/// C type : PyObject*
	@Field(5) 
	public Pointer<PyObject > modules_reloading() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : PyObject*
	@Field(5) 
	public PyInterpreterState modules_reloading(Pointer<PyObject > modules_reloading) {
		this.io.setPointerField(this, 5, modules_reloading);
		return this;
	}
	/// C type : PyObject*
	@Field(6) 
	public Pointer<PyObject > codec_search_path() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : PyObject*
	@Field(6) 
	public PyInterpreterState codec_search_path(Pointer<PyObject > codec_search_path) {
		this.io.setPointerField(this, 6, codec_search_path);
		return this;
	}
	/// C type : PyObject*
	@Field(7) 
	public Pointer<PyObject > codec_search_cache() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : PyObject*
	@Field(7) 
	public PyInterpreterState codec_search_cache(Pointer<PyObject > codec_search_cache) {
		this.io.setPointerField(this, 7, codec_search_cache);
		return this;
	}
	/// C type : PyObject*
	@Field(8) 
	public Pointer<PyObject > codec_error_registry() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : PyObject*
	@Field(8) 
	public PyInterpreterState codec_error_registry(Pointer<PyObject > codec_error_registry) {
		this.io.setPointerField(this, 8, codec_error_registry);
		return this;
	}
	@Field(9) 
	public int dlopenflags() {
		return this.io.getIntField(this, 9);
	}
	@Field(9) 
	public PyInterpreterState dlopenflags(int dlopenflags) {
		this.io.setIntField(this, 9, dlopenflags);
		return this;
	}
	public PyInterpreterState(Pointer pointer) {
		super(pointer);
	}
}
