package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : classobject.h:19</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyInstanceObject extends StructObject {
	public PyInstanceObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PyInstanceObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyInstanceObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/**
	 * The class object<br>
	 * C type : PyClassObject*
	 */
	@Field(2) 
	public Pointer<PyClassObject > in_class() {
		return this.io.getPointerField(this, 2);
	}
	/**
	 * The class object<br>
	 * C type : PyClassObject*
	 */
	@Field(2) 
	public PyInstanceObject in_class(Pointer<PyClassObject > in_class) {
		this.io.setPointerField(this, 2, in_class);
		return this;
	}
	/**
	 * A dictionary<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public Pointer<PyObject > in_dict() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * A dictionary<br>
	 * C type : PyObject*
	 */
	@Field(3) 
	public PyInstanceObject in_dict(Pointer<PyObject > in_dict) {
		this.io.setPointerField(this, 3, in_dict);
		return this;
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public Pointer<PyObject > in_weakreflist() {
		return this.io.getPointerField(this, 4);
	}
	/**
	 * List of weak references<br>
	 * C type : PyObject*
	 */
	@Field(4) 
	public PyInstanceObject in_weakreflist(Pointer<PyObject > in_weakreflist) {
		this.io.setPointerField(this, 4, in_weakreflist);
		return this;
	}
	public PyInstanceObject(Pointer pointer) {
		super(pointer);
	}
}
