package com.heeere.python27;
import com.heeere.python27.Python27Library.binaryfunc;
import com.heeere.python27.Python27Library.objobjargproc;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : object.h:124</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyMappingMethods extends StructObject {
	public PyMappingMethods() {
		super();
	}
	/// C type : binaryfunc
	@Field(1) 
	public Pointer<binaryfunc > mp_subscript() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : binaryfunc
	@Field(1) 
	public PyMappingMethods mp_subscript(Pointer<binaryfunc > mp_subscript) {
		this.io.setPointerField(this, 1, mp_subscript);
		return this;
	}
	/// C type : objobjargproc
	@Field(2) 
	public Pointer<objobjargproc > mp_ass_subscript() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : objobjargproc
	@Field(2) 
	public PyMappingMethods mp_ass_subscript(Pointer<objobjargproc > mp_ass_subscript) {
		this.io.setPointerField(this, 2, mp_ass_subscript);
		return this;
	}
	public PyMappingMethods(Pointer pointer) {
		super(pointer);
	}
}
