package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : memoryobject.h:18</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyMemoryViewObject extends StructObject {
	public PyMemoryViewObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PyMemoryViewObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyMemoryViewObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > base() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PyMemoryViewObject base(Pointer<PyObject > base) {
		this.io.setPointerField(this, 2, base);
		return this;
	}
	/// C type : Py_buffer
	@Field(3) 
	public Py_buffer view() {
		return this.io.getNativeObjectField(this, 3);
	}
	/// C type : Py_buffer
	@Field(3) 
	public PyMemoryViewObject view(Py_buffer view) {
		this.io.setNativeObjectField(this, 3, view);
		return this;
	}
	public PyMemoryViewObject(Pointer pointer) {
		super(pointer);
	}
}
