package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : stringobject.h:7</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyStringObject extends StructObject {
	public PyStringObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PyStringObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyStringObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(2) 
	public long ob_size() {
		return this.io.getSizeTField(this, 2);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(2) 
	public PyStringObject ob_size(long ob_size) {
		this.io.setSizeTField(this, 2, ob_size);
		return this;
	}
	@CLong 
	@Field(3) 
	public long ob_shash() {
		return this.io.getCLongField(this, 3);
	}
	@CLong 
	@Field(3) 
	public PyStringObject ob_shash(long ob_shash) {
		this.io.setCLongField(this, 3, ob_shash);
		return this;
	}
	@Field(4) 
	public int ob_sstate() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public PyStringObject ob_sstate(int ob_sstate) {
		this.io.setIntField(this, 4, ob_sstate);
		return this;
	}
	/// C type : char[1]
	@Array({1}) 
	@Field(5) 
	public Pointer<Byte > ob_sval() {
		return this.io.getPointerField(this, 5);
	}
	public PyStringObject(Pointer pointer) {
		super(pointer);
	}
}
