package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : pyerrors.h:39</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PySystemExitObject extends StructObject {
	public PySystemExitObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PySystemExitObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PySystemExitObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > dict() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PySystemExitObject dict(Pointer<PyObject > dict) {
		this.io.setPointerField(this, 2, dict);
		return this;
	}
	/// C type : PyObject*
	@Field(3) 
	public Pointer<PyObject > args() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : PyObject*
	@Field(3) 
	public PySystemExitObject args(Pointer<PyObject > args) {
		this.io.setPointerField(this, 3, args);
		return this;
	}
	/// C type : PyObject*
	@Field(4) 
	public Pointer<PyObject > message() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : PyObject*
	@Field(4) 
	public PySystemExitObject message(Pointer<PyObject > message) {
		this.io.setPointerField(this, 4, message);
		return this;
	}
	/// C type : PyObject*
	@Field(5) 
	public Pointer<PyObject > code() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : PyObject*
	@Field(5) 
	public PySystemExitObject code(Pointer<PyObject > code) {
		this.io.setPointerField(this, 5, code);
		return this;
	}
	public PySystemExitObject(Pointer pointer) {
		super(pointer);
	}
}
