package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : pyerrors.h:19</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PySyntaxErrorObject extends StructObject {
	public PySyntaxErrorObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PySyntaxErrorObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PySyntaxErrorObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > dict() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PySyntaxErrorObject dict(Pointer<PyObject > dict) {
		this.io.setPointerField(this, 2, dict);
		return this;
	}
	/// C type : PyObject*
	@Field(3) 
	public Pointer<PyObject > args() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : PyObject*
	@Field(3) 
	public PySyntaxErrorObject args(Pointer<PyObject > args) {
		this.io.setPointerField(this, 3, args);
		return this;
	}
	/// C type : PyObject*
	@Field(4) 
	public Pointer<PyObject > message() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : PyObject*
	@Field(4) 
	public PySyntaxErrorObject message(Pointer<PyObject > message) {
		this.io.setPointerField(this, 4, message);
		return this;
	}
	/// C type : PyObject*
	@Field(5) 
	public Pointer<PyObject > msg() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : PyObject*
	@Field(5) 
	public PySyntaxErrorObject msg(Pointer<PyObject > msg) {
		this.io.setPointerField(this, 5, msg);
		return this;
	}
	/// C type : PyObject*
	@Field(6) 
	public Pointer<PyObject > filename() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : PyObject*
	@Field(6) 
	public PySyntaxErrorObject filename(Pointer<PyObject > filename) {
		this.io.setPointerField(this, 6, filename);
		return this;
	}
	/// C type : PyObject*
	@Field(7) 
	public Pointer<PyObject > lineno() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : PyObject*
	@Field(7) 
	public PySyntaxErrorObject lineno(Pointer<PyObject > lineno) {
		this.io.setPointerField(this, 7, lineno);
		return this;
	}
	/// C type : PyObject*
	@Field(8) 
	public Pointer<PyObject > offset() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : PyObject*
	@Field(8) 
	public PySyntaxErrorObject offset(Pointer<PyObject > offset) {
		this.io.setPointerField(this, 8, offset);
		return this;
	}
	/// C type : PyObject*
	@Field(9) 
	public Pointer<PyObject > text() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : PyObject*
	@Field(9) 
	public PySyntaxErrorObject text(Pointer<PyObject > text) {
		this.io.setPointerField(this, 9, text);
		return this;
	}
	/// C type : PyObject*
	@Field(10) 
	public Pointer<PyObject > print_file_and_line() {
		return this.io.getPointerField(this, 10);
	}
	/// C type : PyObject*
	@Field(10) 
	public PySyntaxErrorObject print_file_and_line(Pointer<PyObject > print_file_and_line) {
		this.io.setPointerField(this, 10, print_file_and_line);
		return this;
	}
	public PySyntaxErrorObject(Pointer pointer) {
		super(pointer);
	}
}
