package com.heeere.python27;
import com.heeere.python27.Python27Library.Py_ssize_t;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : pyerrors.h:31</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyUnicodeErrorObject extends StructObject {
	public PyUnicodeErrorObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public Pointer<Py_ssize_t > ob_refcnt() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : Py_ssize_t
	@Field(0) 
	public PyUnicodeErrorObject ob_refcnt(Pointer<Py_ssize_t > ob_refcnt) {
		this.io.setPointerField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyUnicodeErrorObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/// C type : PyObject*
	@Field(2) 
	public Pointer<PyObject > dict() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : PyObject*
	@Field(2) 
	public PyUnicodeErrorObject dict(Pointer<PyObject > dict) {
		this.io.setPointerField(this, 2, dict);
		return this;
	}
	/// C type : PyObject*
	@Field(3) 
	public Pointer<PyObject > args() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : PyObject*
	@Field(3) 
	public PyUnicodeErrorObject args(Pointer<PyObject > args) {
		this.io.setPointerField(this, 3, args);
		return this;
	}
	/// C type : PyObject*
	@Field(4) 
	public Pointer<PyObject > message() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : PyObject*
	@Field(4) 
	public PyUnicodeErrorObject message(Pointer<PyObject > message) {
		this.io.setPointerField(this, 4, message);
		return this;
	}
	/// C type : PyObject*
	@Field(5) 
	public Pointer<PyObject > encoding() {
		return this.io.getPointerField(this, 5);
	}
	/// C type : PyObject*
	@Field(5) 
	public PyUnicodeErrorObject encoding(Pointer<PyObject > encoding) {
		this.io.setPointerField(this, 5, encoding);
		return this;
	}
	/// C type : PyObject*
	@Field(6) 
	public Pointer<PyObject > object() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : PyObject*
	@Field(6) 
	public PyUnicodeErrorObject object(Pointer<PyObject > object) {
		this.io.setPointerField(this, 6, object);
		return this;
	}
	/// C type : Py_ssize_t
	@Field(7) 
	public Pointer<Py_ssize_t > start() {
		return this.io.getPointerField(this, 7);
	}
	/// C type : Py_ssize_t
	@Field(7) 
	public PyUnicodeErrorObject start(Pointer<Py_ssize_t > start) {
		this.io.setPointerField(this, 7, start);
		return this;
	}
	/// C type : Py_ssize_t
	@Field(8) 
	public Pointer<Py_ssize_t > end() {
		return this.io.getPointerField(this, 8);
	}
	/// C type : Py_ssize_t
	@Field(8) 
	public PyUnicodeErrorObject end(Pointer<Py_ssize_t > end) {
		this.io.setPointerField(this, 8, end);
		return this;
	}
	/// C type : PyObject*
	@Field(9) 
	public Pointer<PyObject > reason() {
		return this.io.getPointerField(this, 9);
	}
	/// C type : PyObject*
	@Field(9) 
	public PyUnicodeErrorObject reason(Pointer<PyObject > reason) {
		this.io.setPointerField(this, 9, reason);
		return this;
	}
	public PyUnicodeErrorObject(Pointer pointer) {
		super(pointer);
	}
}
