package com.heeere.python27;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.CLong;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Ptr;
/**
 * <i>native declaration : unicodeobject.h:12</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class PyUnicodeObject extends StructObject {
	public PyUnicodeObject() {
		super();
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public long ob_refcnt() {
		return this.io.getSizeTField(this, 0);
	}
	/// C type : Py_ssize_t
	@Ptr 
	@Field(0) 
	public PyUnicodeObject ob_refcnt(long ob_refcnt) {
		this.io.setSizeTField(this, 0, ob_refcnt);
		return this;
	}
	/// C type : _typeobject*
	@Field(1) 
	public Pointer<PyTypeObject > ob_type() {
		return this.io.getPointerField(this, 1);
	}
	/// C type : _typeobject*
	@Field(1) 
	public PyUnicodeObject ob_type(Pointer<PyTypeObject > ob_type) {
		this.io.setPointerField(this, 1, ob_type);
		return this;
	}
	/**
	 * Length of raw Unicode data in buffer<br>
	 * C type : Py_ssize_t
	 */
	@Ptr 
	@Field(2) 
	public long length() {
		return this.io.getSizeTField(this, 2);
	}
	/**
	 * Length of raw Unicode data in buffer<br>
	 * C type : Py_ssize_t
	 */
	@Ptr 
	@Field(2) 
	public PyUnicodeObject length(long length) {
		this.io.setSizeTField(this, 2, length);
		return this;
	}
	/**
	 * Raw Unicode buffer<br>
	 * C type : Py_UNICODE*
	 */
	@Field(3) 
	public Pointer<Integer > str() {
		return this.io.getPointerField(this, 3);
	}
	/**
	 * Raw Unicode buffer<br>
	 * C type : Py_UNICODE*
	 */
	@Field(3) 
	public PyUnicodeObject str(Pointer<Integer > str) {
		this.io.setPointerField(this, 3, str);
		return this;
	}
	/// Hash value; -1 if not set
	@CLong 
	@Field(4) 
	public long hash() {
		return this.io.getCLongField(this, 4);
	}
	/// Hash value; -1 if not set
	@CLong 
	@Field(4) 
	public PyUnicodeObject hash(long hash) {
		this.io.setCLongField(this, 4, hash);
		return this;
	}
	/**
	 * (Default) Encoded version as Python<br>
	 * string, or NULL; this is used for<br>
	 * implementing the buffer protocol<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public Pointer<PyObject > defenc() {
		return this.io.getPointerField(this, 5);
	}
	/**
	 * (Default) Encoded version as Python<br>
	 * string, or NULL; this is used for<br>
	 * implementing the buffer protocol<br>
	 * C type : PyObject*
	 */
	@Field(5) 
	public PyUnicodeObject defenc(Pointer<PyObject > defenc) {
		this.io.setPointerField(this, 5, defenc);
		return this;
	}
	public PyUnicodeObject(Pointer pointer) {
		super(pointer);
	}
}
