package com.heeere.python27;
import com.heeere.python27.Python27Library.wrapperfunc;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * <i>native declaration : descrobject.h:20</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("python27") 
public class wrapperbase extends StructObject {
	public wrapperbase() {
		super();
	}
	/// C type : char*
	@Field(0) 
	public Pointer<Byte > name() {
		return this.io.getPointerField(this, 0);
	}
	/// C type : char*
	@Field(0) 
	public wrapperbase name(Pointer<Byte > name) {
		this.io.setPointerField(this, 0, name);
		return this;
	}
	@Field(1) 
	public int offset() {
		return this.io.getIntField(this, 1);
	}
	@Field(1) 
	public wrapperbase offset(int offset) {
		this.io.setIntField(this, 1, offset);
		return this;
	}
	/// C type : void*
	@Field(2) 
	public Pointer<? > function() {
		return this.io.getPointerField(this, 2);
	}
	/// C type : void*
	@Field(2) 
	public wrapperbase function(Pointer<? > function) {
		this.io.setPointerField(this, 2, function);
		return this;
	}
	/// C type : wrapperfunc
	@Field(3) 
	public Pointer<wrapperfunc > wrapper() {
		return this.io.getPointerField(this, 3);
	}
	/// C type : wrapperfunc
	@Field(3) 
	public wrapperbase wrapper(Pointer<wrapperfunc > wrapper) {
		this.io.setPointerField(this, 3, wrapper);
		return this;
	}
	/// C type : char*
	@Field(4) 
	public Pointer<Byte > doc() {
		return this.io.getPointerField(this, 4);
	}
	/// C type : char*
	@Field(4) 
	public wrapperbase doc(Pointer<Byte > doc) {
		this.io.setPointerField(this, 4, doc);
		return this;
	}
	@Field(5) 
	public int flags() {
		return this.io.getIntField(this, 5);
	}
	@Field(5) 
	public wrapperbase flags(int flags) {
		this.io.setIntField(this, 5, flags);
		return this;
	}
	/// C type : PyObject*
	@Field(6) 
	public Pointer<PyObject > name_strobj() {
		return this.io.getPointerField(this, 6);
	}
	/// C type : PyObject*
	@Field(6) 
	public wrapperbase name_strobj(Pointer<PyObject > name_strobj) {
		this.io.setPointerField(this, 6, name_strobj);
		return this;
	}
	public wrapperbase(Pointer pointer) {
		super(pointer);
	}
}
